name: Compilar Launcher
on:
  push:
    branches: [ master ] # Cambiado a master porque esa es tu rama principal

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publicar Ejecutable
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:ReadyToRun=true -o ./dist

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: LatamLauncher-Windows
        path: ./dist/*.exe
